## numpy array operations


In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("neg index",arr[-3])



# 2d array here we are doing slicing in 2d arr
arr_2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]]
)
print("the 2 d array",arr_2d)
print("specific element r,c",arr_2d[1,2])

print("\n entire row",arr_2d[1])

#  all rown and specific column
print("\n entire col",arr_2d[:,1])

basic slicing [3 4 5 6 7]
with step [2 4 6 8]
neg index 7
the 2 d array [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element r,c 6

 entore row [4 5 6]

 entore col [2 5 8]


SORTING

In [13]:
import numpy as np
unsorted=np.array([3,4,5,6,7,7,8,9,3,3])

print("sorted array",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("sorted array in 2 d  col wise",np.sort(arr_2d_unsorted,axis=0))

print("sorted array in 2 d  row  wise",np.sort(arr_2d_unsorted,axis=1))


sorted array [3 3 3 4 5 6 7 7 8 9]
sorted array in 2 d  col wise [[1 1]
 [2 2]
 [3 3]]
sorted array in 2 d  row  wise [[1 3]
 [1 2]
 [2 3]]


In [14]:
# Filter in array

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8])
even_number=numbers[numbers%2 ==0]
print("even",even_number)


even [2 4 6 8]


In [17]:
# Filter with mask

In [19]:
mask = numbers > 5
print("numbers grt 5",numbers[mask])

numbers grt 5 [6 7 8]


In [20]:
# fancy indexing and vs np.where()

In [24]:
indices = [0,1,2]
print(numbers[indices])


where_result = np.where(numbers > 5)
print(" np where",numbers[ where_result])



# conditipn arr
con_arr = np.where(numbers > 5,numbers*4,numbers)
print(con_arr)

[1 2 3]
 np where [6 7 8]
[ 1  2  3  4  5 24 28 32]


Adding and removing data


In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,7,8])
com = np.concatenate((arr1,arr2))
print("the combined arr",com)

the combined arr [1 2 3 5 7 8]
