## Numpy array and basics here
learn about numpy



import numpy as np

In [3]:
import numpy as np


creating array 

In [ ]:
arr_1d = np.array([1,2,3,4])
print("here we are having 1d arr",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("here we are having 2d arr",arr_2d)



np_arr = np.array([1,2,3])
print("arr multi",np_arr*2)

array vs list

In [ ]:
import time
start = time.time()

py_list = [i*2 for i in range(1000)]
print("\n list ops time:",time.time() - start)



start = time.time()
np_arr = np.arange(10000) * 2
print("/n list ops time:",time.time() - start)

Creating arr from scratch


In [ ]:
zeros = np.zeros((3,4))
print("zero arr:\n",zeros)


ones=np.ones((2,3))
print("zero arr:\n",ones)


full =np.full((2,2),7)
print("zero arr:\n",full)


random=np.random.random((2,3))
print("zero arr:\n",random)


sequence=np.arange(0,10,2)
print("zero arr:\n",sequence)

# filled a array with a specific value
full_arr = np.full((2,2))
print(full_arr)



# identity array

iden_matrix=npl= np.eye(4)
print(iden_matrix)


vector,matrix,tensor

In [19]:
vector = np.array(([1,2,3]))
print("vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix",matrix)



tensor=np.array([[[1,2],[4,5]],
                [[5,6],[7,8]] ])
print("tensor:\n",tensor)


vector: [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2]
  [4 5]]

 [[5 6]
  [7 8]]]


Array prop


In [22]:
arr=np.array([[1,2,3],
            [4,5,6]])

print("shape",arr.shape)
print("dimenstion",arr.ndim)
print("size",arr.size)
print("datatype",arr.dtype)


shape (2, 3)
dimenstion 2
size 6
datatype int64


Array reshaping

In [29]:
arr=np.arange(12)
print("original array",arr)

reshape = arr.reshape([3,4])
print("reshape array",reshape)


# copy returned
flattened=reshape.flatten()
print("flattened array",flattened)

# return view instead of copy
raveled = reshape.ravel()
print("\n the revaled array",raveled)



# Transpose matrix convert row into column and column into row
transpose = reshape.T
print("\n the transpose array",transpose)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 the revaled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 the transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
# maths operations
arr= np.array([10,20,30])
print(arr + 5)
print(arr *2)
print(arr -2)

[15 25 35]
[20 40 60]
[ 8 18 28]
